server:
    port: 8081

spring:
    cloud:
        stream:
            kafka:
                binder:
                    replication-factor: 1
            bindings:
                accountMessageChannel:
                    destination: "account"
                    content-type: "application/json"
